# Generated by Django 5.2.4 on 2025-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('bank_order_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(default='NEW', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('customer_id', models.CharField(max_length=64)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=16)),
                ('payment_links_web', models.URLField(blank=True, default='')),
                ('sdk_payload', models.JSONField(blank=True, null=True)),
                ('last_status_payload', models.JSONField(blank=True, null=True)),
                ('txn_id', models.CharField(blank=True, default='', max_length=128)),
                ('payment_method_type', models.CharField(blank=True, default='', max_length=32)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('auth_type', models.CharField(blank=True, default='', max_length=32)),
                ('refunded', models.BooleanField(default=False)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('order_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
