# Generated by Django 5.2.4 on 2026-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NityaSevaAutoCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('seva_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_handle', models.CharField(blank=True, max_length=100)),
                ('wants_80g', models.BooleanField(default=False)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('txnid', models.CharField(max_length=100, unique=True)),
                ('access_key', models.CharField(blank=True, max_length=500)),
                ('mandate_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('easebuzz_payment_id', models.CharField(blank=True, max_length=200)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nitya Seva Auto Collect',
                'ordering': ['-created_at'],
            },
        ),
    ]
