# Generated by Django 5.2.4 on 2026-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_nitya_seva_autocollect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nityasevaautocollect',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nitya Seva InstaCollect'},
        ),
        migrations.RemoveField(
            model_name='nityasevaautocollect',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='nityasevaautocollect',
            name='easebuzz_payment_id',
        ),
        migrations.RemoveField(
            model_name='nityasevaautocollect',
            name='mandate_id',
        ),
        migrations.RemoveField(
            model_name='nityasevaautocollect',
            name='upi_handle',
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='last_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='order_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='qr_code_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='upi_vpa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='va_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='va_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nityasevaautocollect',
            name='va_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nityasevaautocollect',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
