# Generated by Django 5.2.4 on 2025-08-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=40, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(blank=True, max_length=40)),
                ("currency", models.CharField(default="INR", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=12,
                    ),
                ),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "gateway_txn_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("raw_req", models.JSONField(blank=True, null=True)),
                ("raw_resp", models.JSONField(blank=True, null=True)),
                ("webhook", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
