# Generated by Django 5.1.5 on 2025-01-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
