# Generated by Django 5.1.5 on 2025-01-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_banner_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage')),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
    ]
