# Generated by Django 5.2.4 on 2025-07-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_top_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='top_header',
            new_name='TopHeader',
        ),
    ]
