# Generated by Django 5.1.5 on 2025-07-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_rename_banner_to_Banner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="top_header",
            new_name="TopHeader",
        ),
    ]
