# Generated by Django 5.2.4 on 2025-08-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_rename_top_header_topheader"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPopup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage/news")),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("link_url", models.URLField(blank=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
