# Generated by Django 5.2.4 on 2026-08-05 23:23

import django.core.validators
import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_newspopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='homepage', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), homepage.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='newspopup',
            name='image',
            field=models.ImageField(upload_to='homepage/news', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), homepage.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='topheader',
            name='image',
            field=models.ImageField(upload_to='homepage', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), homepage.models.validate_image_file_size]),
        ),
    ]
