"""
Django settings for iskcongkp project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import os.path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

HDFC_SMART = {
    "BASE_URL": os.environ.get("HDFC_BASE_URL", "https://smartgatewayuat.hdfcbank.com"),
    "API_KEY": os.environ.get("HDFC_API_KEY"),
    "MERCHANT_ID": os.environ.get("HDFC_MERCHANT_ID"),
    "CLIENT_ID": os.environ.get("HDFC_CLIENT_ID"),  # 'hdfcmaster' on UAT
    "RESPONSE_KEY": os.environ.get("HDFC_RESPONSE_KEY"),
    "RETURN_URL": os.environ.get("HDFC_RETURN_URL"),
}

_required_hdfc_keys = ["BASE_URL", "API_KEY", "MERCHANT_ID", "CLIENT_ID", "RESPONSE_KEY", "RETURN_URL"]
_missing_hdfc_keys = [k for k in _required_hdfc_keys if not HDFC_SMART.get(k)]
if _missing_hdfc_keys:
    raise ImproperlyConfigured(
        "Missing HDFC_SMART settings: " + ", ".join(_missing_hdfc_keys)
    )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'payment',
    'donation',
    'homepage',
    'who_we_are',
    'festivals',
    'services',
    'django_cleanup.apps.CleanupConfig', # should go after your apps
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'iskcongkp.middleware.MaintenanceModeMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iskcongkp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iskcongkp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'iskcongkp',
        'USER': os.environ.get("DATABASE_USER"),
        'PASSWORD': os.environ.get("DATABASE_PASSWORD"),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# assets paths

STATIC_URL = '/assets/'
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# media paths
MEDIA_URL = "/media/"  # django storage
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# user redirect
#LOGIN_REDIRECT_URL = "home"
#LOGOUT_REDIRECT_URL = "home"

# CkEditor
#CKEDITOR_UPLOAD_PATH = "uploads/"

# Social login Django allauth settings
SITE_ID = 1
MAINTENANCE_MODE = False
